type Repository {
    id: ID
    url: String
    name: String
    guid: String
    jira_instance_url: String
    jira_project_key: String
    repo_branches: [RepoBranch]
}

type RepoBranch {
    id: ID!
    branch: String!
    included_extensions: [String]!
    status: String
    name: String
    guid: String
    jira_instance_url: String
    jira_project_key: String
    services: [Service]!
    clients: [Client]!
}

type Service {
    id: ID
    port: Int!
    exposed_endpoints: [Endpoint]!
}

type Client {
    id: ID
    consumed_endpoints: [Endpoint]!
}

type Endpoint {
    id: ID
    url: String!
    method: String!
    description: String!
    specification: String!
}

type AffectedEndpoint {
    id: ID
    url: String!
    method: String!
    changeType: String!
    description: String!
    reason: String!
    changeOrigin: String!
    originUniqueID: String!
    changeOriginURL: String!
    status: String
}
type GithubProject{
    repository: String!
    branch: String!
    prId: String
    prUrl: String
}

type JiraProject {
    url: String!
    id: String!
    ticketId: String
    ticketUrl: String
}

type AffectedClient{
    name: String!
    guid: String!
    githubProject: GithubProject
    jiraProject: JiraProject
}

type OriginatingService{
    name: String!
    guid: String!
    githubProject: GithubProject
    jiraProject: JiraProject
    affectedEndpoint: AffectedEndpoint!
}

type ActionItem {
    id: ID!
    type: String!
    comments: String
    propagationStatus: String!
    originatingService: OriginatingService!
    affectedClient: AffectedClient!
}

type Query {
    repositories: [Repository]
    repository(id: ID!): Repository
    services: [Service]
    service(id: ID!): Service
    clients: [Client]
    client(id: ID!): Client
    endpoints: [Endpoint]
    endpoint(url: String, method: String): [Endpoint]
    affectedEndpoints: [AffectedEndpoint]
    actionItems: [ActionItem]
}

type Mutation {
    onboardRepository(url: String!, branch: String!, included_extensions: [String]!): Repository!
    notifyAffectedEndpoints(url: String!, method: String!, changeType: String!, description: String!, reason: String!, changeOrigin: String!, originUniqueID: String!, changeOriginURL: String!): AffectedEndpoint!
    # updateActionItem(id: ID!, actionItem: ActionItem!) ActionItem
}