# data = {
#     "timestamp": 1739965442008,
#     "webhookEvent": "jira:issue_updated",
#     "issue_event_type_name": "issue_generic",
#     "user": {
#         "self": "http://localhost:8080/rest/api/2/user?key=JIRAUSER10000",
#         "name": "Sakthivel.ganesan",
#         "key": "JIRAUSER10000",
#         "emailAddress": "sms2sakthivel@gmail.com",
#         "displayName": "Sakthivel Ganesan",
#     },
#     "issue": {
#         "id": "10000",
#         "self": "http://localhost:8080/rest/api/2/issue/10000",
#         "key": "USERMAN-1",
#         "fields": {
#             "issuetype": {
#                 "self": "http://localhost:8080/rest/api/2/issuetype/10001",
#                 "id": "10001",
#                 "description": "Created by Jira Software - do not edit or delete. Issue type for a user story.",
#                 "iconUrl": "http://localhost:8080/images/icons/issuetypes/story.svg",
#                 "name": "Story",
#                 "subtask": False,
#                 "avatarId": None,
#             },
#             "timespent": None,
#             "project": {
#                 "self": "http://localhost:8080/rest/api/2/project/10000",
#                 "id": "10000",
#                 "key": "USERMAN",
#                 "name": "User Manager",
#                 "projectTypeKey": "software",
#                 "avatarUrls": {
#                     "48x48": "http://localhost:8080/secure/projectavatar?avatarId=10324",
#                     "24x24": "http://localhost:8080/secure/projectavatar?size=small&avatarId=10324",
#                     "16x16": "http://localhost:8080/secure/projectavatar?size=xsmall&avatarId=10324",
#                     "32x32": "http://localhost:8080/secure/projectavatar?size=medium&avatarId=10324",
#                 },
#                 "projectCategory": None,
#             },
#             "fixVersions": [],
#             "customfield_10110": None,
#             "customfield_10111": None,
#             "aggregatetimespent": None,
#             "resolution": {
#                 "self": "http://localhost:8080/rest/api/2/resolution/10000",
#                 "id": "10000",
#                 "description": "Work has been completed on this issue.",
#                 "iconUrl": None,
#                 "name": "Done",
#             },
#             "customfield_10106": None,
#             "customfield_10107": None,
#             "customfield_10108": None,
#             "customfield_10109": None,
#             "resolutiondate": "2025-02-19T11:44:02.002+0000",
#             "workratio": -1,
#             "lastViewed": "2025-02-19T11:44:01.995+0000",
#             "watches": {
#                 "self": "http://localhost:8080/rest/api/2/issue/USERMAN-1/watchers",
#                 "watchCount": 1,
#                 "watchers": None,
#                 "isWatching": True,
#             },
#             "created": "2025-02-18T14:45:14.593+0000",
#             "priority": {
#                 "self": "http://localhost:8080/rest/api/2/priority/2",
#                 "statusColor": None,
#                 "description": None,
#                 "iconUrl": "http://localhost:8080/images/icons/priorities/high.svg",
#                 "name": "High",
#                 "id": "2",
#             },
#             "customfield_10100": "0|hzzzzz:",
#             "customfield_10101": None,
#             "customfield_10102": None,
#             "labels": ["userman"],
#             "timeestimate": None,
#             "aggregatetimeoriginalestimate": None,
#             "versions": [],
#             "issuelinks": [],
#             "assignee": {
#                 "self": "http://localhost:8080/rest/api/2/user?username=raj_bhawan",
#                 "name": "raj_bhawan",
#                 "key": "JIRAUSER10100",
#                 "emailAddress": "raj@gmail.com",
#                 "avatarUrls": {
#                     "48x48": "https://www.gravatar.com/avatar/f1614e532ca522391d1de570af561c56?d=mm&s=48",
#                     "24x24": "https://www.gravatar.com/avatar/f1614e532ca522391d1de570af561c56?d=mm&s=24",
#                     "16x16": "https://www.gravatar.com/avatar/f1614e532ca522391d1de570af561c56?d=mm&s=16",
#                     "32x32": "https://www.gravatar.com/avatar/f1614e532ca522391d1de570af561c56?d=mm&s=32",
#                 },
#                 "displayName": "Raj Bhawan Singh",
#                 "active": True,
#                 "timeZone": "Etc/UTC",
#             },
#             "updated": "2025-02-19T11:44:02.004+0000",
#             "status": {
#                 "self": "http://localhost:8080/rest/api/2/status/10001",
#                 "statusColor": None,
#                 "description": "",
#                 "iconUrl": "http://localhost:8080/",
#                 "name": "Done",
#                 "id": "10001",
#                 "statusCategory": {
#                     "self": "http://localhost:8080/rest/api/2/statuscategory/3",
#                     "id": 3,
#                     "key": "done",
#                     "colorName": "success",
#                     "name": "Done",
#                 },
#             },
#             "components": [],
#             "timeoriginalestimate": None,
#             "description": "The Phone number attribute is missing in the Users Attributes List and needs to be added.",
#             "timetracking": {
#                 "originalEstimate": None,
#                 "remainingEstimate": None,
#                 "timeSpent": None,
#                 "originalEstimateSeconds": None,
#                 "remainingEstimateSeconds": None,
#                 "timeSpentSeconds": None,
#             },
#             "archiveddate": None,
#             "attachment": [
#                 {
#                     "self": "http://localhost:8080/rest/api/2/attachment/10000",
#                     "id": "10000",
#                     "filename": "swagger.yaml",
#                     "author": {
#                         "self": "http://localhost:8080/rest/api/2/user?username=Sakthivel.ganesan",
#                         "name": "Sakthivel.ganesan",
#                         "key": "JIRAUSER10000",
#                         "emailAddress": "sms2sakthivel@gmail.com",
#                         "avatarUrls": {
#                             "48x48": "http://localhost:8080/secure/useravatar?avatarId=10346",
#                             "24x24": "http://localhost:8080/secure/useravatar?size=small&avatarId=10346",
#                             "16x16": "http://localhost:8080/secure/useravatar?size=xsmall&avatarId=10346",
#                             "32x32": "http://localhost:8080/secure/useravatar?size=medium&avatarId=10346",
#                         },
#                         "displayName": "Sakthivel Ganesan",
#                         "active": True,
#                         "timeZone": "Asia/Kolkata",
#                     },
#                     "created": "2025-02-18T14:59:36.681+0000",
#                     "size": 4753,
#                     "mimeType": "application/x-yaml",
#                     "content": "http://localhost:8080/secure/attachment/10000/swagger.yaml",
#                     "thumbnail": None,
#                 }
#             ],
#             "aggregatetimeestimate": None,
#             "summary": "Add Phone Number Attribute in User Attributes",
#             "creator": {
#                 "self": "http://localhost:8080/rest/api/2/user?username=Sakthivel.ganesan",
#                 "name": "Sakthivel.ganesan",
#                 "key": "JIRAUSER10000",
#                 "emailAddress": "sms2sakthivel@gmail.com",
#                 "avatarUrls": {
#                     "48x48": "http://localhost:8080/secure/useravatar?avatarId=10346",
#                     "24x24": "http://localhost:8080/secure/useravatar?size=small&avatarId=10346",
#                     "16x16": "http://localhost:8080/secure/useravatar?size=xsmall&avatarId=10346",
#                     "32x32": "http://localhost:8080/secure/useravatar?size=medium&avatarId=10346",
#                 },
#                 "displayName": "Sakthivel Ganesan",
#                 "active": True,
#                 "timeZone": "Asia/Kolkata",
#             },
#             "subtasks": [],
#             "reporter": {
#                 "self": "http://localhost:8080/rest/api/2/user?username=Sakthivel.ganesan",
#                 "name": "Sakthivel.ganesan",
#                 "key": "JIRAUSER10000",
#                 "emailAddress": "sms2sakthivel@gmail.com",
#                 "avatarUrls": {
#                     "48x48": "http://localhost:8080/secure/useravatar?avatarId=10346",
#                     "24x24": "http://localhost:8080/secure/useravatar?size=small&avatarId=10346",
#                     "16x16": "http://localhost:8080/secure/useravatar?size=xsmall&avatarId=10346",
#                     "32x32": "http://localhost:8080/secure/useravatar?size=medium&avatarId=10346",
#                 },
#                 "displayName": "Sakthivel Ganesan",
#                 "active": True,
#                 "timeZone": "Asia/Kolkata",
#             },
#             "customfield_10000": '{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@f5333a1[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@28d7f3c0[byInstanceType={},overall=PullRequestOverallBean{stateCount=0, state=\'OPEN\', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@6c12c1ae[byInstanceType={},overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@7b4c661f[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>]], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@183553be[byInstanceType={},overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@330f8296[dueDate=<null>,overDue=false,state=<null>,stateCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>]], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@496a3ae8[byInstanceType={},overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@518ec144[showProjects=false,successfulCount=0,topEnvironments=[],count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>]], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@6394c068[byInstanceType={},overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@2c40f5be[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>]], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@346537a4[byInstanceType={},overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@13c6448d[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>]]},configErrors=[],errors=[]], devSummaryJson={"cachedValue":{"errors":[],"configErrors":[],"summary":{"pullrequest":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":"OPEN","details":{"openCount":0,"mergedCount":0,"declinedCount":0,"total":0},"open":true},"byInstanceType":{}},"build":{"overall":{"count":0,"lastUpdated":null,"failedBuildCount":0,"successfulBuildCount":0,"unknownBuildCount":0},"byInstanceType":{}},"review":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":null,"dueDate":null,"overDue":false,"completed":false},"byInstanceType":{}},"deployment-environment":{"overall":{"count":0,"lastUpdated":null,"topEnvironments":[],"showProjects":false,"successfulCount":0},"byInstanceType":{}},"repository":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}},"branch":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}}}},"isStale":false}}',
#             "aggregateprogress": {"progress": 0, "total": 0, "percent": None},
#             "environment": None,
#             "duedate": None,
#             "progress": {"progress": 0, "total": 0, "percent": None},
#             "comment": {"comments": [], "maxResults": 0, "total": 0, "startAt": 0},
#             "votes": {
#                 "self": "http://localhost:8080/rest/api/2/issue/USERMAN-1/votes",
#                 "votes": 0,
#                 "hasVoted": False,
#                 "voters": None,
#             },
#             "worklog": {"startAt": 0, "maxResults": 20, "total": 0, "worklogs": []},
#             "archivedby": None,
#         },
#         "properties": None,
#         "transitions": None,
#         "renderedFields": None,
#         "names": None,
#         "schema": None,
#         "operations": None,
#         "editmeta": None,
#         "changelog": None,
#         "versionedRepresentations": None,
#     },
#     "changelog": {
#         "id": "10101",
#         "author": None,
#         "created": None,
#         "items": [
#             {
#                 "field": "resolution",
#                 "fieldtype": "jira",
#                 "from": None,
#                 "fromString": None,
#                 "to": "10000",
#                 "toString": "Done",
#             },
#             {
#                 "field": "status",
#                 "fieldtype": "jira",
#                 "from": "3",
#                 "fromString": "In Progress",
#                 "to": "10001",
#                 "toString": "Done",
#             },
#         ],
#     },
# }

data = {
    "endpoint": [
        {
            "id": "2",
            "url": "/users",
            "method": "GET",
            "description": "Retrieve a list of all users.",
            "specification": '{"description": "Retrieve a list of all users", "consumes": ["application/json"], "produces": ["application/json"], "tags": ["Users"], "summary": "Get All Users", "responses": {"200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/model.UserResponse"}}}, "500": {"description": "Internal Server Error", "schema": {"$ref": "#/definitions/fiber.Error"}}}, "definitions": {"fiber.Error": {"type": "object", "properties": {"code": {"type": "integer"}, "message": {"type": "string"}}}, "model.UserResponse": {"type": "object", "properties": {"email": {"type": "string"}, "name": {"type": "string"}, "user_id": {"type": "integer"}, "user_name": {"type": "string"}}}}}',
        }
    ]
}
