# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

EXPOSE 9502

# Specify the command to run the application (adjust as needed)
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "9502"]